# Deploy to Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescue-app
  namespace: testingopentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescue-app
  template:
    metadata:
      labels:
        app: rescue-app
    spec:
      containers:
      - name: rescue-app
        image: karin86/pythonapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: rescue-app
spec:
  selector:
    app: rescue-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000