receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug: {}
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]